# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'AXAttributedStringDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for AXAttributedStringDemo

  pod 'AXAttributedString', :path => '../../../AXAttributedString'

  target 'AXAttributedStringDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AXAttributedStringDemoUITests' do
    # Pods for testing
  end

end
